export const TECHNICIAN_PAYMENTS_ENABLED = false;
export const COMPLIANCE_CRON_ENABLED = false;
export const TENANT_SELF_BOOKING_ENABLED = false;
export const AUTOMATED_COMPLETED_JOB_DOCUMENTS_ENABLED = true;
